# Generated by Django 3.0.2 on 2020-02-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('designation', models.CharField(choices=[('manager', 'MANAGER'), ('hrhead', 'HRHEAD'), ('interviewer', 'INTERVIEWER'), ('employee', 'EMPLOYEE')], max_length=12)),
                ('address', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
